# Generated by Django 4.2.23 on 2026-01-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestap', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('phone_number', models.CharField(max_length=13, verbose_name='телефон')),
                ('reqires_delivery', models.BooleanField(default=False, verbose_name='требуется доставка')),
                ('delivery', models.TextField(blank=True, null=True, verbose_name='адрес доставки')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='оплата при получении')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачен')),
                ('status', models.CharField(default='в обработке...', max_length=36, verbose_name='статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
            },
        ),
    ]
