# Generated by Django 4.2.23 on 2026-01-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='reqires_delivery',
            new_name='requires_delivery',
        ),
    ]
